<?php
/**
 * Interview Result PDF - Recruitment
 * Detailed interview result for a single applicant
 */
$reportTitle = 'INTERVIEW RESULT';
$reportSubtitle = htmlspecialchars($session['full_name'] ?? 'Applicant') . ' — ' . htmlspecialchars($session['question_bank_name'] ?? 'Interview');
$score = (float)($session['total_score'] ?? 0);
$logoPath = function_exists('asset') ? asset('images/logo.jpg') : '/PT_indoocean/PT_indoocean/recruitment/public/assets/images/logo.jpg';
?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Interview Result - <?= htmlspecialchars($session['full_name'] ?? '') ?></title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <style>
        @page { size: A4; margin: 12mm 15mm; }
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Inter', sans-serif; font-size: 9pt; color: #1a1a2e; background: #fff; line-height: 1.5; }
        .pdf-container { max-width: 800px; margin: 0 auto; padding: 25px; }
        .company-header { display: flex; align-items: center; gap: 18px; padding-bottom: 12px; border-bottom: 3px solid #1e3a5f; }
        .company-logo { width: 55px; height: 55px; border-radius: 50%; overflow: hidden; border: 2px solid #1e3a5f; }
        .company-logo img { width: 55px; height: 55px; object-fit: cover; }
        .company-info h1 { font-size: 12pt; font-weight: 800; color: #1e3a5f; }
        .company-info p { font-size: 7pt; color: #666; }
        .title-bar { background: linear-gradient(135deg, #1e3a5f, #2c5282, #3182ce); color: #fff; text-align: center; padding: 10px; margin: 12px 0; border-radius: 6px; }
        .title-bar h2 { font-size: 12pt; font-weight: 800; letter-spacing: 2px; }
        .title-bar .sub { font-size: 8pt; opacity: 0.85; }
        .meta { display: flex; justify-content: space-between; font-size: 8pt; color: #666; margin-bottom: 12px; padding: 6px 0; border-bottom: 1px dashed #ddd; }
        .summary-grid { display: flex; gap: 10px; margin-bottom: 15px; }
        .summary-card { flex: 1; background: linear-gradient(135deg, #f0f4f8, #e8edf3); border: 1px solid #d1d9e6; border-radius: 8px; padding: 12px; text-align: center; }
        .summary-card .label { font-size: 7pt; font-weight: 700; color: #64748b; text-transform: uppercase; }
        .summary-card .value { font-size: 20pt; font-weight: 800; color: #1e3a5f; }
        .score-green { color: #16a34a !important; }
        .score-amber { color: #d97706 !important; }
        .score-red { color: #dc2626 !important; }
        .qa-block { margin-bottom: 12px; page-break-inside: avoid; border: 1px solid #e2e8f0; border-radius: 6px; overflow: hidden; }
        .qa-header { background: #f0f4f8; padding: 8px 12px; font-weight: 700; font-size: 8.5pt; color: #1e3a5f; display: flex; justify-content: space-between; }
        .qa-body { padding: 10px 12px; }
        .qa-body .question { font-weight: 600; color: #475569; font-size: 8.5pt; margin-bottom: 6px; }
        .qa-body .answer { background: #f8fafc; padding: 8px; border-radius: 4px; font-size: 8.5pt; border-left: 3px solid #2563eb; }
        .qa-body .feedback { margin-top: 6px; padding: 6px 8px; background: #fefce8; border-radius: 4px; font-size: 7.5pt; color: #854d0e; }
        .badge { display: inline-block; padding: 2px 8px; border-radius: 10px; font-size: 7pt; font-weight: 700; }
        .badge-green { background: #dcfce7; color: #166534; }
        .badge-amber { background: #fef3c7; color: #92400e; }
        .badge-red { background: #fee2e2; color: #991b1b; }
        .footer { margin-top: 20px; padding-top: 10px; border-top: 2px solid #1e3a5f; display: flex; justify-content: space-between; font-size: 7pt; color: #94a3b8; }
        @media print { body { background: #fff; } .pdf-container { padding: 0; } .no-print { display: none !important; } }
        @media screen { body { background: #e2e8f0; padding: 20px; } .pdf-container { background: #fff; box-shadow: 0 4px 25px rgba(0,0,0,0.12); border-radius: 10px; padding: 35px; } }
    </style>
</head>
<body>
<div class="pdf-container">
    <div class="company-header">
        <div class="company-logo"><img src="<?= $logoPath ?>" alt="Logo"></div>
        <div class="company-info">
            <h1>PT. INDO OCEAN CREW SERVICES</h1>
            <p>Menara Cakrawala Lt. 15 No. 1506, Jl. M.H. Thamrin No. 9, Jakarta Pusat</p>
        </div>
    </div>
    <div class="title-bar">
        <h2>AI INTERVIEW RESULT</h2>
        <div class="sub"><?= htmlspecialchars($session['question_bank_name'] ?? 'Interview') ?></div>
    </div>
    <div class="meta">
        <span>📅 <?= date('d F Y') ?></span>
        <span style="font-style:italic; color:#999;">Generated by IndoOcean Recruitment System</span>
    </div>

    <!-- Applicant Info & Score -->
    <div class="summary-grid">
        <div class="summary-card" style="flex:2; text-align:left; padding:12px 14px;">
            <table style="font-size:8.5pt; width:100%;">
                <tr><td style="width:100px; font-weight:700; color:#475569; padding:3px 0;">Applicant</td><td style="font-weight:800; color:#1e3a5f;"><?= htmlspecialchars($session['full_name'] ?? '-') ?></td></tr>
                <tr><td style="font-weight:700; color:#475569; padding:3px 0;">Email</td><td><?= htmlspecialchars($session['email'] ?? '-') ?></td></tr>
                <tr><td style="font-weight:700; color:#475569; padding:3px 0;">Vacancy</td><td><?= htmlspecialchars($session['vacancy_title'] ?? '-') ?></td></tr>
                <tr><td style="font-weight:700; color:#475569; padding:3px 0;">Completed</td><td><?= !empty($session['completed_at']) ? date('d/m/Y H:i', strtotime($session['completed_at'])) : 'In Progress' ?></td></tr>
            </table>
        </div>
        <div class="summary-card">
            <div class="label">Total Score</div>
            <div class="value <?= $score >= 70 ? 'score-green' : ($score >= 50 ? 'score-amber' : 'score-red') ?>"><?= number_format($score, 1) ?>%</div>
        </div>
        <div class="summary-card">
            <div class="label">Recommendation</div>
            <div style="font-size:10pt; font-weight:700; color:#1e3a5f; margin-top:8px;">
                <?php
                $rec = $session['ai_recommendation'] ?? '';
                if (stripos($rec, 'recommend') !== false || $score >= 70) echo '<span class="badge badge-green" style="font-size:9pt">RECOMMENDED</span>';
                elseif ($score >= 50) echo '<span class="badge badge-amber" style="font-size:9pt">REVIEW</span>';
                else echo '<span class="badge badge-red" style="font-size:9pt">NOT RECOMMENDED</span>';
                ?>
            </div>
        </div>
    </div>

    <!-- Q&A Detail -->
    <h3 style="font-size:10pt; font-weight:700; color:#1e3a5f; margin-bottom:10px; border-bottom:2px solid #e2e8f0; padding-bottom:5px;">📝 Question & Answer Detail</h3>
    
    <?php if (!empty($answers)): ?>
        <?php foreach ($answers as $i => $a): 
            $qScore = (float)($a['score'] ?? 0);
            $maxScore = (float)($a['max_score'] ?? 10);
            $pct = $maxScore > 0 ? ($qScore / $maxScore * 100) : 0;
        ?>
        <div class="qa-block">
            <div class="qa-header">
                <span>Q<?= $i + 1 ?>. <?= htmlspecialchars(substr($a['question_text'] ?? '', 0, 80)) ?><?= strlen($a['question_text'] ?? '') > 80 ? '...' : '' ?></span>
                <span>
                    <span class="badge <?= $pct >= 70 ? 'badge-green' : ($pct >= 50 ? 'badge-amber' : 'badge-red') ?>">
                        <?= number_format($qScore, 1) ?> / <?= $maxScore ?>
                    </span>
                </span>
            </div>
            <div class="qa-body">
                <div class="question"><?= htmlspecialchars($a['question_text'] ?? '-') ?></div>
                <div class="answer"><?= nl2br(htmlspecialchars($a['answer_text'] ?? 'No answer provided')) ?></div>
                <?php if (!empty($a['ai_feedback'])): ?>
                <div class="feedback">💡 <strong>AI Feedback:</strong> <?= htmlspecialchars($a['ai_feedback']) ?></div>
                <?php endif; ?>
            </div>
        </div>
        <?php endforeach; ?>
    <?php else: ?>
        <p style="text-align:center; color:#999; padding:20px;">No answers recorded for this interview session.</p>
    <?php endif; ?>

    <?php if (!empty($session['admin_notes'])): ?>
    <div style="margin-top:12px; padding:10px; background:#f0f4f8; border-left:4px solid #1e3a5f; border-radius:4px; font-size:8pt;">
        <strong>📝 Admin Notes:</strong> <?= nl2br(htmlspecialchars($session['admin_notes'])) ?>
    </div>
    <?php endif; ?>

    <div class="footer">
        <span style="font-weight:700; color:#1e3a5f;">🔒 CONFIDENTIAL — PT. Indo Ocean Crew Services</span>
        <span>Printed: <?= date('d/m/Y H:i') ?></span>
    </div>
</div>

<div class="no-print" style="text-align:center; margin:20px auto; max-width:800px;">
    <button onclick="window.print()" style="padding:12px 40px; background:linear-gradient(135deg,#1e3a5f,#2c5282); color:#fff; border:none; border-radius:10px; font-weight:700; cursor:pointer; font-size:14px; font-family:'Inter',sans-serif;">
        🖨️ Print / Save as PDF
    </button>
    <button onclick="window.history.back()" style="padding:12px 40px; background:#f1f5f9; color:#475569; border:1px solid #cbd5e1; border-radius:10px; font-weight:600; cursor:pointer; font-size:14px; font-family:'Inter',sans-serif; margin-left:10px;">
        ← Back
    </button>
</div>
</body>
</html>
